
const SUPABASE_URL='https://kzwuycfgvztlvyfbkimh.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_s1rAqIVAN71PcKfEEatVIA_CpgHlF_L';
const cloud=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=id=>document.getElementById(id), n=v=>Number(v)||0, fmt=v=>Number(v).toLocaleString('en-MY',{maximumFractionDigits:3}), today=()=>new Date().toISOString().slice(0,10);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const state={customers:[],weights:[],production:[],deliveries:[],resorts:[]};
let currentProfile=null,realtimeChannel=null,realtimeReloadTimer=null,realtimeFallbackTimer=null;
function customerById(id){return state.customers.find(x=>x.id===id)}
function weightById(id){return state.weights.find(x=>x.id===id)}
function productionView(r){return {...r,customer:customerById(r.customer_id)?.name||'Unknown',weight:n(weightById(r.weight_id)?.weight_kg)}}
function allowedFor(role,el){return (el.dataset.roles||'admin,production,store').split(',').includes(role)}
function activateFirstAllowed(role){const btn=[...document.querySelectorAll('.nav button')].find(b=>allowedFor(role,b));if(btn)btn.click()}
function applyRoleUI(role){document.querySelectorAll('.nav button[data-roles]').forEach(b=>b.hidden=!allowedFor(role,b));const active=document.querySelector('.nav button.active');if(!active||active.hidden)activateFirstAllowed(role)}
function optionCustomers(value='',empty='Select customer'){return `<option value="">${empty}</option>`+state.customers.map(x=>`<option value="${x.id}" ${x.id===value?'selected':''}>${esc(x.name)}</option>`).join('')}
function optionWeights(value='',empty='Select weight'){return `<option value="">${empty}</option>`+state.weights.map(x=>`<option value="${x.id}" ${x.id===value?'selected':''}>${fmt(x.weight_kg)} kg</option>`).join('')}
function refreshSelects(){
 for(const id of ['pCustomer','dCustomer','dRecipientCustomer','prodFilterCustomer','deliveryFilterCustomer','rCustomer']){const el=$(id),old=el.value;el.innerHTML=optionCustomers(old,id.includes('Filter')?'All customers':'Select customer')}
 const old=$('pWeight').value;$('pWeight').innerHTML=optionWeights(old);
 refreshDeliveryWeights();refreshResortWeights();
}
function inventoryRows(){const map={};const keyOf=(customerId,weightId)=>customerId+'||'+weightId;const ensureProduction=(customerId,weightId)=>{const key=keyOf(customerId,weightId),customer=customerById(customerId),weight=weightById(weightId);if(!customer||!weight)return null;if(!map[key])map[key]={customerId,weightId,customer:customer.name,weight:n(weight.weight_kg),pass:0,fail:0,resorted:0,delivered:0};return map[key]};
 state.production.filter(r=>!r.deleted_at).forEach(r=>{const x=ensureProduction(r.customer_id,r.weight_id);if(!x)return;x.pass+=n(r.pass_bags);x.fail+=n(r.fail_bags)});
 state.resorts.filter(r=>!r.deleted_at).forEach(r=>{const x=map[keyOf(r.customer_id,r.weight_id)];if(x)x.resorted+=n(r.bags)});
 state.deliveries.filter(r=>!r.deleted_at).forEach(r=>{const x=map[keyOf(r.customer_id,r.weight_id)];if(x)x.delivered+=n(r.bags)});
 return Object.values(map).map(x=>{const remainingFail=Math.max(0,x.fail-x.resorted),available=Math.max(0,x.pass+x.resorted-x.delivered),weight=n(x.weight);return {...x,weight,remainingFail,remainingFailKg:remainingFail*weight,available,availableKg:available*weight}}).filter(x=>x.pass||x.fail||x.resorted||x.delivered).sort((a,b)=>a.customer.localeCompare(b.customer)||a.weight-b.weight)}
function stock(customerId,weightId,ignore=''){const row=inventoryRows().find(x=>x.customerId===customerId&&x.weightId===weightId);let available=row?.available||0;const old=state.deliveries.find(x=>x.id===ignore);if(old&&old.customer_id===customerId&&old.weight_id===weightId&&!old.deleted_at)available+=n(old.bags);return available}
function refreshDeliveryWeights(selected){const customerId=$('dCustomer').value,old=selected??$('dWeight').value;const rows=inventoryRows().filter(r=>r.customerId===customerId&&r.available>0);$('dWeight').innerHTML='<option value="">Select weight</option>'+rows.map(r=>`<option value="${r.weightId}" ${r.weightId===old?'selected':''}>${fmt(r.weight)} kg — ${fmt(r.available)} bags available</option>`).join('')}
function refreshResortWeights(){const customerId=$('rCustomer').value,old=$('rWeight').value;const rows=inventoryRows().filter(r=>r.customerId===customerId&&r.remainingFail>0);$('rWeight').innerHTML='<option value="">'+(customerId?'Select weight':'Select customer first')+'</option>'+rows.map(r=>`<option value="${r.weightId}" ${r.weightId===old?'selected':''}>${fmt(r.weight)} kg — ${fmt(r.remainingFail)} fail bags</option>`).join('');updateResortCheck()}
function updateResortCheck(){const c=$('rCustomer').value,w=$('rWeight').value,row=inventoryRows().find(x=>x.customerId===c&&x.weightId===w),remaining=row?.remainingFail||0,weight=row?.weight||0,bags=n($('rBags').value);$('rRemaining').textContent=fmt(remaining);$('rRemainingWeight').textContent=fmt(remaining*weight)+' kg';const invalid=!c||!w||bags<=0||bags>remaining;$('resortSubmit').disabled=invalid;$('resortNotice').innerHTML=!c||!w||!bags?'':bags>remaining?`<div class="notice bad">Cannot exceed Remaining Fail Bags (${fmt(remaining)} bags).</div>`:`<div class="notice ok">After re-sort: ${fmt(remaining-bags)} fail bags remaining; ${fmt(bags)} bags will be added to Finished Goods.</div>`}
function renderTop(){const t=today(),pr=state.production.filter(r=>!r.deleted_at&&r.production_date===t),out=pr.reduce((a,r)=>a+n(r.pass_bags)+n(r.fail_bags),0),pass=pr.reduce((a,r)=>a+n(r.pass_bags),0),fail=pr.reduce((a,r)=>a+n(r.fail_bags),0),available=inventoryRows().reduce((a,r)=>a+r.available,0);$('topToday').textContent=fmt(out);$('topPass').textContent=fmt(pass);$('topStock').textContent=fmt(available);$('prodOutput').textContent=fmt(out);$('prodPass').textContent=fmt(pass);$('prodFail').textContent=fmt(fail);$('prodRate').textContent=out?((pass/out)*100).toFixed(1)+'%':'0%'}
function renderProduction(){let rows=state.production.filter(r=>!r.deleted_at).map(productionView).sort((a,b)=>(b.production_date+b.created_at).localeCompare(a.production_date+a.created_at));const fd=$('prodFilterDate').value,fc=$('prodFilterCustomer').value;if(fd)rows=rows.filter(r=>r.production_date===fd);if(fc)rows=rows.filter(r=>r.customer_id===fc);if(!rows.length){$('productionTable').innerHTML='<div class="empty">No Pass / Fail records.</div>';return}$('productionTable').innerHTML=`<div class="table-wrap"><table><thead><tr><th>Record</th><th>Date</th><th>Shift</th><th>Customer</th><th>Pass Bags</th><th>Pass Weight</th><th>Fail Bags</th><th>Fail Weight</th><th>Total Bags</th><th>kg / Bag</th><th>Remark</th><th>Action</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.record_number)}</td><td>${r.production_date}</td><td>${r.shift}</td><td><strong>${esc(r.customer)}</strong></td><td><span class="pill ok">${r.pass_bags}</span></td><td>${fmt(n(r.pass_bags)*r.weight)} kg</td><td><span class="pill bad">${r.fail_bags}</span></td><td>${fmt(n(r.fail_bags)*r.weight)} kg</td><td>${n(r.pass_bags)+n(r.fail_bags)}</td><td>${fmt(r.weight)}</td><td>${esc(r.remark||'-')}</td><td><div class="row-actions"><button class="icon-btn" onclick="editProduction('${r.id}')">Edit</button><button class="icon-btn" onclick="deleteProduction('${r.id}')">Delete</button></div></td></tr>`).join('')}</tbody></table></div>`}
function renderDelivery(){let rows=state.deliveries.filter(r=>!r.deleted_at).sort((a,b)=>(b.delivery_date+b.created_at).localeCompare(a.delivery_date+a.created_at));const fd=$('deliveryFilterDate').value,fc=$('deliveryFilterCustomer').value;if(fd)rows=rows.filter(r=>r.delivery_date===fd);if(fc)rows=rows.filter(r=>r.customer_id===fc);if(!rows.length){$('deliveryTable').innerHTML='<div class="empty">No cloud delivery records.</div>';return}$('deliveryTable').innerHTML=`<div class="table-wrap"><table><thead><tr><th>Record</th><th>Date</th><th>Customer</th><th>Bags</th><th>kg / Bag</th><th>Total Weight</th><th>Delivered To</th><th>Reference</th><th>Remark</th><th>Action</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.record_number)}</td><td>${r.delivery_date}</td><td><strong>${esc(customerById(r.customer_id)?.name||'Unknown')}</strong></td><td>${r.bags}</td><td>${fmt(weightById(r.weight_id)?.weight_kg||0)}</td><td>${fmt(n(r.bags)*n(weightById(r.weight_id)?.weight_kg))} kg</td><td>${esc(customerById(r.delivered_to_customer_id)?.name||'-')}</td><td>${esc(r.reference||'-')}</td><td>${esc(r.remark||'-')}</td><td><div class="row-actions"><button class="icon-btn" onclick="editDelivery('${r.id}')">Edit</button><button class="icon-btn" onclick="deleteDelivery('${r.id}')">Delete</button></div></td></tr>`).join('')}</tbody></table></div>`}
function renderInventory(){const rows=inventoryRows().filter(r=>r.pass||r.fail||r.resorted||r.delivered);if(!rows.length){$('inventoryTable').innerHTML='<div class="empty">No inventory yet.</div>';return}$('inventoryTable').innerHTML=`<div class="table-wrap"><table style="min-width:980px"><thead><tr><th>Customer</th><th>Net Weight / Bag</th><th>Total Fail Bags</th><th>Total Fail Weight</th><th>Available Bags</th><th>Available Weight</th><th>Status</th></tr></thead><tbody>${rows.map(r=>{const status=r.available<=0?'<span class="pill bad">Out of Stock</span>':r.available<=5?'<span class="pill warn">Low Stock</span>':'<span class="pill ok">Available</span>';return `<tr><td><strong>${esc(r.customer)}</strong></td><td><strong>${fmt(r.weight)} kg</strong></td><td><span class="pill bad">${fmt(r.remainingFail)}</span></td><td>${fmt(r.remainingFailKg)} kg</td><td><strong>${fmt(r.available)}</strong></td><td>${fmt(r.availableKg)} kg</td><td>${status}</td></tr>`}).join('')}</tbody></table></div>`}
function renderSettings(){$('customerList').innerHTML=state.customers.length?state.customers.map(c=>`<div class="list-row"><div><strong>${esc(c.name)}</strong></div><div class="row-actions"><button class="icon-btn" onclick="renameCustomer('${c.id}')">Edit</button><button class="icon-btn" onclick="removeCustomer('${c.id}')">Delete</button></div></div>`).join(''):'<div class="empty">No customers.</div>';$('weightList').innerHTML=state.weights.length?state.weights.map(w=>`<div class="list-row"><div><strong>${fmt(w.weight_kg)} kg</strong></div><div class="row-actions"><button class="icon-btn" onclick="renameWeight('${w.id}')">Edit</button><button class="icon-btn" onclick="removeWeight('${w.id}')">Delete</button></div></div>`).join(''):'<div class="empty">No weight presets.</div>'}
function renderAll(){refreshSelects();renderTop();renderProduction();renderDelivery();renderInventory();renderSettings();updatePTotal();updateDeliveryCheck();updateResortCheck()}
function updatePTotal(){$('pTotal').value=n($('pPass').value)+n($('pFail').value)+' bags'}
function updateDeliveryCheck(){const c=$('dCustomer').value,w=$('dWeight').value,id=$('deliveryId').value,available=c&&w?stock(c,w,id):0,bags=n($('dBags').value);$('dAvailable').value=available+' bags';$('dAfter').value=(available-bags)+' bags';$('deliveryNotice').innerHTML=!c||!w||!bags?'':bags>available?`<div class="notice bad">Insufficient stock. Short by <strong>${bags-available} bags</strong>.</div>`:`<div class="notice ok">Stock is sufficient. Remaining <strong>${available-bags} bags</strong>.</div>`}
async function loadCloudData(){const [c,w,p,d,r]=await Promise.all([cloud.from('customers').select('id,name,created_at').is('deleted_at',null).eq('is_active',true).order('name'),cloud.from('weight_presets').select('id,weight_kg,created_at').is('deleted_at',null).eq('is_active',true).order('weight_kg'),cloud.from('production_records').select('id,record_number,production_date,shift,customer_id,pass_bags,fail_bags,weight_id,remark,version,created_at,updated_at,deleted_at').is('deleted_at',null).order('production_date',{ascending:false}).order('created_at',{ascending:false}),cloud.from('delivery_records').select('id,record_number,delivery_date,customer_id,bags,weight_id,delivered_to_customer_id,reference,remark,version,created_at,updated_at,deleted_at').is('deleted_at',null).order('delivery_date',{ascending:false}).order('created_at',{ascending:false}),cloud.from('resort_transactions').select('id,customer_id,weight_id,bags,remark,created_at,deleted_at').is('deleted_at',null).order('created_at',{ascending:false})]);for(const x of [c,w,p,d,r])if(x.error)throw x.error;state.customers=c.data||[];state.weights=w.data||[];state.production=p.data||[];state.deliveries=d.data||[];state.resorts=r.data||[];renderAll()}
async function productionSubmit(e){e.preventDefault();if(!currentProfile||!['admin','production'].includes(currentProfile.role))return alert('No permission.');const id=$('productionId').value,payload={production_date:$('pDate').value,shift:$('pShift').value,customer_id:$('pCustomer').value,pass_bags:n($('pPass').value),fail_bags:n($('pFail').value),weight_id:$('pWeight').value,remark:$('pRemark').value.trim()||null};if(!payload.customer_id||!payload.weight_id)return alert('Please select customer and net weight.');if(payload.pass_bags+payload.fail_bags<=0)return alert('Pass Bags and Fail Bags cannot both be empty or 0.');const btn=e.submitter;btn.disabled=true;btn.textContent='Saving…';const q=id?cloud.from('production_records').update(payload).eq('id',id):cloud.from('production_records').insert(payload);const {error}=await q;btn.disabled=false;btn.textContent='Save Record';if(error)return alert(error.message);resetProduction();await loadCloudData();if(currentProfile.role==='admin')loadAudit()}
function resetProduction(){$('productionForm').reset();$('productionId').value='';$('pDate').value=today();$('pPass').value='';$('pFail').value='';$('cancelProduction').hidden=true;updatePTotal();refreshSelects()}
window.editProduction=id=>{const r=state.production.find(x=>x.id===id);if(!r)return;$('productionId').value=r.id;$('pDate').value=r.production_date;$('pShift').value=r.shift;$('pCustomer').value=r.customer_id;$('pPass').value=r.pass_bags;$('pFail').value=r.fail_bags;$('pWeight').value=r.weight_id;$('pRemark').value=r.remark||'';$('cancelProduction').hidden=false;updatePTotal();document.querySelector('[data-tab="production"]').click();scrollTo({top:0,behavior:'smooth'})}
window.deleteProduction=async id=>{if(!confirm('Delete this production record? It remains in Audit Log.'))return;const {error}=await cloud.from('production_records').update({deleted_at:new Date().toISOString(),deleted_by:currentProfile.id}).eq('id',id);if(error)return alert(error.message);await loadCloudData();if(currentProfile.role==='admin')loadAudit()}
$('deliveryForm').addEventListener('submit',async e=>{e.preventDefault();if(!currentProfile||!['admin','store'].includes(currentProfile.role))return alert('No permission.');const id=$('deliveryId').value,payload={delivery_date:$('dDate').value,customer_id:$('dCustomer').value,bags:n($('dBags').value),weight_id:$('dWeight').value,delivered_to_customer_id:$('dRecipientCustomer').value||null,reference:$('dRecipient').value.trim()||null,remark:$('dRemark').value.trim()||null};const available=stock(payload.customer_id,payload.weight_id,id);if(!payload.customer_id||!payload.weight_id||payload.bags<1)return alert('Please complete delivery information.');if(payload.bags>available)return alert(`Insufficient stock. Available: ${available} bags. Requested: ${payload.bags} bags.`);const btn=e.submitter;btn.disabled=true;btn.textContent='Saving…';const q=id?cloud.from('delivery_records').update(payload).eq('id',id):cloud.from('delivery_records').insert(payload);const {error}=await q;btn.disabled=false;btn.textContent='Save Delivery';if(error)return alert(error.message);resetDelivery();await loadCloudData();if(currentProfile.role==='admin')loadAudit()});
function resetDelivery(){$('deliveryForm').reset();$('deliveryId').value='';$('dDate').value=today();$('cancelDelivery').hidden=true;refreshSelects();updateDeliveryCheck()}
window.editDelivery=id=>{const r=state.deliveries.find(x=>x.id===id);if(!r)return;$('deliveryId').value=r.id;$('dDate').value=r.delivery_date;$('dCustomer').value=r.customer_id;refreshDeliveryWeights(r.weight_id);$('dBags').value=r.bags;$('dWeight').value=r.weight_id;$('dRecipientCustomer').value=r.delivered_to_customer_id||'';$('dRecipient').value=r.reference||'';$('dRemark').value=r.remark||'';$('cancelDelivery').hidden=false;updateDeliveryCheck()}
window.deleteDelivery=async id=>{if(!confirm('Delete this delivery record? It remains in Audit Log.'))return;const {error}=await cloud.from('delivery_records').update({deleted_at:new Date().toISOString(),deleted_by:currentProfile.id}).eq('id',id);if(error)return alert(error.message);await loadCloudData();if(currentProfile.role==='admin')loadAudit()}
$('newCustomer').addEventListener('input',e=>{const pos=e.target.selectionStart;e.target.value=e.target.value.toUpperCase();e.target.setSelectionRange(pos,pos)});$('addCustomer').onclick=async()=>{const name=$('newCustomer').value.trim().toUpperCase();if(!name)return;const duplicate=state.customers.some(c=>c.name.toUpperCase()===name);if(duplicate)return alert('Customer already exists.');const {error}=await cloud.from('customers').insert({name});if(error)return alert(error.message);$('newCustomer').value='';await loadCloudData()}
$('addWeight').onclick=async()=>{const weight_kg=n($('newWeight').value);if(weight_kg<=0)return;const {error}=await cloud.from('weight_presets').insert({weight_kg});if(error)return alert(error.message);$('newWeight').value='';await loadCloudData()}
window.renameCustomer=async id=>{const c=customerById(id),name=prompt('Edit customer name',c?.name)?.trim().toUpperCase();if(!name||name===c.name)return;if(state.customers.some(x=>x.id!==id&&x.name.toUpperCase()===name))return alert('Customer already exists.');const {error}=await cloud.from('customers').update({name,updated_by:currentProfile.id}).eq('id',id);if(error)return alert(error.message);await loadCloudData()}
window.removeCustomer=async id=>{if(state.production.some(r=>r.customer_id===id))return alert('This customer is used in Production records and cannot be deleted. Edit the name instead.');if(!confirm('Delete this customer?'))return;const {error}=await cloud.from('customers').update({deleted_at:new Date().toISOString(),deleted_by:currentProfile.id,is_active:false}).eq('id',id);if(error)return alert(error.message);await loadCloudData()}
window.renameWeight=async id=>{const w=weightById(id),weight_kg=n(prompt('Edit net weight (kg)',w?.weight_kg));if(weight_kg<=0||weight_kg===n(w.weight_kg))return;const {error}=await cloud.from('weight_presets').update({weight_kg,updated_by:currentProfile.id}).eq('id',id);if(error)return alert(error.message);await loadCloudData()}
window.removeWeight=async id=>{if(state.production.some(r=>r.weight_id===id))return alert('This weight is used in Production records and cannot be deleted. Edit it instead.');if(!confirm('Delete this weight?'))return;const {error}=await cloud.from('weight_presets').update({deleted_at:new Date().toISOString(),deleted_by:currentProfile.id,is_active:false}).eq('id',id);if(error)return alert(error.message);await loadCloudData()}
async function writeLoginAudit(){await cloud.from('audit_logs').insert({action:'LOGIN',module:'authentication',record_type:'session',new_data:{user_agent:navigator.userAgent}})}
async function loadProfile(user){const {data,error}=await cloud.from('profiles').select('id,email,full_name,employee_id,role,status,last_login_at').eq('id',user.id).single();if(error)throw new Error(error.message);if(data.status!=='active'){await cloud.auth.signOut();const messages={pending:'Your account is waiting for Admin approval.',disabled:'This account is disabled. Please contact an Administrator.',deleted:'This account has been deleted. Please contact an Administrator.'};throw new Error(messages[data.status]||'This account is not active.')}currentProfile=data;$('currentUserName').textContent=data.full_name||data.email;$('currentRole').textContent=data.role;$('accountAvatar').textContent=(data.full_name||data.email||'U').trim().charAt(0).toUpperCase();$('userBox').style.display='flex';applyRoleUI(data.role);await cloud.rpc('mark_login');await writeLoginAudit();if(data.role!=='qc'){await loadCloudData();subscribeRealtime()}if(data.role==='admin'){await loadUsers();await loadAudit()} window.dispatchEvent(new CustomEvent('fgms:profile',{detail:data}))}
async function handleSession(session){if(!session){currentProfile=null;$('authScreen').style.display='grid';$('userBox').style.display='none';if(realtimeChannel){await cloud.removeChannel(realtimeChannel);realtimeChannel=null}stopRealtimeFallback();return}try{await loadProfile(session.user);$('authScreen').style.display='none'}catch(err){$('loginError').textContent=err.message}}
function scheduleRealtimeReload(){clearTimeout(realtimeReloadTimer);realtimeReloadTimer=setTimeout(()=>loadCloudData().catch(err=>console.error('Realtime reload failed:',err)),150)}
function startRealtimeFallback(){clearInterval(realtimeFallbackTimer);realtimeFallbackTimer=setInterval(()=>{if(currentProfile&&!document.hidden)loadCloudData().catch(()=>{})},5000)}
function stopRealtimeFallback(){clearInterval(realtimeFallbackTimer);realtimeFallbackTimer=null}
function subscribeRealtime(){
 if(realtimeChannel)cloud.removeChannel(realtimeChannel);
 realtimeChannel=cloud.channel('fgms-build3-realtime-'+currentProfile.id)
  .on('postgres_changes',{event:'*',schema:'public',table:'customers'},scheduleRealtimeReload)
  .on('postgres_changes',{event:'*',schema:'public',table:'weight_presets'},scheduleRealtimeReload)
  .on('postgres_changes',{event:'*',schema:'public',table:'production_records'},scheduleRealtimeReload)
  .on('postgres_changes',{event:'*',schema:'public',table:'delivery_records'},scheduleRealtimeReload)
  .on('postgres_changes',{event:'*',schema:'public',table:'resort_transactions'},scheduleRealtimeReload)
  .subscribe(status=>{
    console.log('FGMS Realtime status:',status);
    if(status==='SUBSCRIBED')scheduleRealtimeReload();
  });
 startRealtimeFallback();
}
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&currentProfile)loadCloudData().catch(()=>{})});
window.addEventListener('focus',()=>{if(currentProfile)loadCloudData().catch(()=>{})});
async function adminManageUser(action,user_id,role=null){const {data,error}=await cloud.rpc('admin_manage_user',{p_action:action,p_user_id:user_id,p_role:role});if(error)throw new Error(error.message);if(!data?.ok)throw new Error(data?.error||'User management action failed.');return data}
function statusPill(status){return status==='active'?'<span class="pill ok">Active</span>':status==='pending'?'<span class="pill warn">Pending Approval</span>':status==='deleted'?'<span class="pill bad">Deleted</span>':'<span class="pill bad">Disabled</span>'}
async function loadUsers(){const {data,error}=await cloud.from('profiles').select('id,email,full_name,employee_id,role,status,last_login_at,created_at').order('created_at',{ascending:false});if(error){$('userManagementTable').innerHTML=`<div class="notice bad">${esc(error.message)}</div>`;return}const users=data||[];$('userManagementTable').innerHTML=users.length?`<div class="table-wrap"><table style="min-width:1050px"><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th><th>Last Login</th><th>Actions</th></tr></thead><tbody>${users.map(u=>{const self=u.id===currentProfile.id;const roleSelect=`<select id="role-${u.id}" ${self?'disabled':''}><option value="production" ${u.role==='production'?'selected':''}>Production</option><option value="store" ${u.role==='store'?'selected':''}>Store / Delivery</option><option value="qc" ${u.role==='qc'?'selected':''}>QC</option><option value="supervisor" ${u.role==='supervisor'?'selected':''}>Supervisor</option><option value="admin" ${u.role==='admin'?'selected':''}>Admin</option></select>`;let actions='';if(u.status==='pending')actions=`<button class="icon-btn" onclick="approveUser('${u.id}')">Approve</button><button class="icon-btn" onclick="rejectUser('${u.id}')">Reject</button>`;else if(u.status==='deleted')actions=`<button class="icon-btn" onclick="restoreUser('${u.id}')">Restore</button>`;else if(!self)actions=`<button class="icon-btn" onclick="saveUserRole('${u.id}')">Save Role</button><button class="icon-btn" onclick="toggleUserStatus('${u.id}',${u.status==='active'})">${u.status==='active'?'Disable':'Enable'}</button><button class="icon-btn" onclick="deleteUserAccount('${u.id}','${esc(u.full_name||u.email)}')">Delete</button>`;else actions='<span class="muted">Current account</span>';return `<tr><td><strong>${esc(u.full_name||'-')}</strong></td><td>${esc(u.email)}</td><td>${roleSelect}</td><td>${statusPill(u.status)}</td><td>${u.last_login_at?new Date(u.last_login_at).toLocaleString('en-MY'):'Never'}</td><td><div class="row-actions">${actions}</div></td></tr>`}).join('')}</tbody></table></div>`:'<div class="empty">No users found.</div>'}
window.approveUser=async id=>{const role=$(`role-${id}`).value;if(!confirm(`Approve this user as ${role}?`))return;try{await adminManageUser('approve',id,role);showUserMessage('User approved and activated.','ok');await loadUsers();await loadAudit()}catch(e){showUserMessage(e.message,'bad')}}
window.rejectUser=async id=>{if(!confirm('Reject and soft delete this registration?'))return;try{await adminManageUser('delete',id);showUserMessage('Registration rejected.','ok');await loadUsers();await loadAudit()}catch(e){showUserMessage(e.message,'bad')}}
window.saveUserRole=async id=>{const role=$(`role-${id}`).value;if(!confirm(`Change this user to ${role}?`))return;try{await adminManageUser('change_role',id,role);showUserMessage('Role updated.','ok');await loadUsers();await loadAudit()}catch(e){showUserMessage(e.message,'bad');await loadUsers()}}
window.toggleUserStatus=async(id,isActive)=>{if(!confirm(isActive?'Disable this user account?':'Enable this user account?'))return;try{await adminManageUser(isActive?'disable':'enable',id);showUserMessage(isActive?'User disabled.':'User enabled.','ok');await loadUsers();await loadAudit()}catch(e){showUserMessage(e.message,'bad')}}
window.deleteUserAccount=async(id,name)=>{if(!confirm(`Soft delete ${name}? The account cannot sign in, but all history will remain.`))return;try{await adminManageUser('delete',id);showUserMessage('User account deleted.','ok');await loadUsers();await loadAudit()}catch(e){showUserMessage(e.message,'bad')}}
window.restoreUser=async id=>{if(!confirm('Restore this account as Disabled? You can then choose a role and enable it.'))return;try{await adminManageUser('restore',id);showUserMessage('User restored as Disabled.','ok');await loadUsers();await loadAudit()}catch(e){showUserMessage(e.message,'bad')}}
function showUserMessage(message,type){$('userActionMessage').innerHTML=`<div class="notice ${type}">${esc(message)}</div>`;setTimeout(()=>{$('userActionMessage').innerHTML=''},6000)}
async function loadAudit(){
 let q=cloud.from('audit_logs').select('created_at,actor_name,actor_email,actor_role,action,module,record_number').order('created_at',{ascending:false}).limit(1000);
 const from=$('auditFrom')?.value,to=$('auditTo')?.value,user=$('auditUser')?.value.trim(),role=$('auditRole')?.value,module=$('auditModule')?.value.trim(),action=$('auditAction')?.value.trim(),record=$('auditRecord')?.value.trim();
 if(from)q=q.gte('created_at',from+'T00:00:00'); if(to)q=q.lte('created_at',to+'T23:59:59.999'); if(role)q=q.eq('actor_role',role); if(module)q=q.ilike('module','%'+module+'%'); if(action)q=q.ilike('action','%'+action+'%'); if(record)q=q.ilike('record_number','%'+record+'%');
 const {data,error}=await q; let rows=data||[]; if(user){const u=user.toLowerCase();rows=rows.filter(a=>(a.actor_name||'').toLowerCase().includes(u)||(a.actor_email||'').toLowerCase().includes(u))}
 $('auditTable').innerHTML=error?`<div class="notice bad">${esc(error.message)}</div>`:`<div class="table-wrap"><table><thead><tr><th>Time</th><th>User</th><th>Role</th><th>Action</th><th>Module</th><th>Record</th></tr></thead><tbody>${rows.map(a=>`<tr><td>${new Date(a.created_at).toLocaleString('en-MY')}</td><td><strong>${esc(a.actor_name||a.actor_email||'-')}</strong></td><td>${esc(a.actor_role||'-')}</td><td>${esc(a.action)}</td><td>${esc(a.module)}</td><td>${esc(a.record_number||'-')}</td></tr>`).join('')}</tbody></table></div>`}
$('productionForm').addEventListener('submit',productionSubmit);$('cancelProduction').onclick=resetProduction;$('cancelDelivery').onclick=resetDelivery;['pPass','pFail'].forEach(id=>$(id).addEventListener('input',updatePTotal));['dBags','dWeight'].forEach(id=>$(id).addEventListener('input',updateDeliveryCheck));$('dCustomer').addEventListener('change',()=>{refreshDeliveryWeights();updateDeliveryCheck()});$('rCustomer').addEventListener('change',refreshResortWeights);$('rWeight').addEventListener('change',updateResortCheck);$('rBags').addEventListener('input',updateResortCheck);$('resortForm').addEventListener('submit',async e=>{e.preventDefault();if(!currentProfile||!['admin','production'].includes(currentProfile.role))return alert('No permission.');const customer_id=$('rCustomer').value,weight_id=$('rWeight').value,bags=n($('rBags').value),remark=$('rRemark').value.trim()||null,row=inventoryRows().find(x=>x.customerId===customer_id&&x.weightId===weight_id),before=row?.remainingFail||0;if(!customer_id||!weight_id||bags<=0||bags>before)return updateResortCheck();const btn=$('resortSubmit');btn.disabled=true;btn.textContent='Saving…';const {error}=await cloud.from('resort_transactions').insert({customer_id,weight_id,bags,remark,created_by:currentProfile.id});btn.textContent='Confirm Re-sort';if(error){btn.disabled=false;return alert(error.message)}$('rBags').value='';$('rRemark').value='';await loadCloudData();const after=Math.max(0,before-bags);$('resortSuccess').innerHTML=`<div class="success-inline">✓ Re-sort completed. ${fmt(bags)} bags moved to Finished Goods. Remaining fail: ${fmt(after)} bags.</div>`;setTimeout(()=>{$('resortSuccess').innerHTML=''},3000);if(currentProfile.role==='admin')loadAudit()});['prodFilterDate','prodFilterCustomer'].forEach(id=>$(id).addEventListener('input',renderProduction));['deliveryFilterDate','deliveryFilterCustomer'].forEach(id=>$(id).addEventListener('input',renderDelivery));
document.querySelectorAll('.nav button').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b===btn));document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.id===btn.dataset.tab));if(btn.dataset.tab==='audit'&&currentProfile?.role==='admin')loadAudit()});
function switchAuth(mode){const login=mode==='login';$('loginForm').hidden=!login;$('registerForm').hidden=login;$('showLogin').className=login?'btn primary':'btn ghost';$('showRegister').className=login?'btn ghost':'btn primary';$('loginError').textContent='';$('registerMessage').textContent='';$('registerMessage').style.color='var(--bad)'}
$('showLogin').onclick=()=>switchAuth('login');$('showRegister').onclick=()=>switchAuth('register');
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();$('loginButton').disabled=true;$('loginButton').textContent='Signing In…';$('loginError').textContent='';const {error}=await cloud.auth.signInWithPassword({email:$('loginEmail').value.trim(),password:$('loginPassword').value});if(error)$('loginError').textContent=error.message;$('loginButton').disabled=false;$('loginButton').textContent='Sign In'});
$('registerForm').addEventListener('submit',async e=>{e.preventDefault();const password=$('registerPassword').value;if(password!==$('registerConfirm').value){$('registerMessage').textContent='Passwords do not match.';return}const btn=$('registerButton');btn.disabled=true;btn.textContent='Registering…';$('registerMessage').textContent='';const email=$('registerEmail').value.trim().toLowerCase();const {data,error}=await cloud.auth.signUp({email,password,options:{data:{full_name:$('registerName').value.trim(),role:$('registerRole').value}}});if(error){$('registerMessage').textContent=error.message}else{await cloud.auth.signOut();$('registerForm').reset();$('registerMessage').style.color='var(--good)';$('registerMessage').textContent=data.session?'Registration submitted. Wait for Admin approval before signing in.':'Registration submitted. Check your email if confirmation is enabled, then wait for Admin approval.'}btn.disabled=false;btn.textContent='Register Account'});
const workspace=document.querySelector('.workspace');
const sidebarToggle=$('sidebarToggle');
function setSidebarCollapsed(collapsed){workspace.classList.toggle('sidebar-collapsed',collapsed);sidebarToggle.textContent=collapsed?'›':'‹';sidebarToggle.title=collapsed?'Expand sidebar':'Collapse sidebar';sidebarToggle.setAttribute('aria-label',sidebarToggle.title);try{localStorage.setItem('fgmsSidebarCollapsed',collapsed?'1':'0')}catch(e){}}
try{setSidebarCollapsed(localStorage.getItem('fgmsSidebarCollapsed')==='1')}catch(e){setSidebarCollapsed(false)}
sidebarToggle.onclick=()=>setSidebarCollapsed(!workspace.classList.contains('sidebar-collapsed'));
$('signOutButton').onclick=()=>cloud.auth.signOut();
$('pDate').value=today();$('dDate').value=today();renderAll();cloud.auth.onAuthStateChange((_e,s)=>setTimeout(()=>handleSession(s),0));cloud.auth.getSession().then(({data})=>handleSession(data.session));
if('serviceWorker' in navigator)navigator.serviceWorker.getRegistrations().then(rs=>rs.forEach(r=>r.unregister()));if('caches' in window)caches.keys().then(keys=>keys.forEach(k=>caches.delete(k)));

// Build 4 Audit filter controls
['auditApply','auditRefresh'].forEach(id=>{const el=$(id);if(el)el.onclick=()=>currentProfile?.role==='admin'&&loadAudit()});
if($('auditClear'))$('auditClear').onclick=()=>{['auditFrom','auditTo','auditUser','auditRole','auditModule','auditAction','auditRecord'].forEach(id=>{if($(id))$(id).value=''});loadAudit()};
