(() => {
const qcState={projects:[],columns:[],files:[],currentFile:null,currentRows:[],builderColumns:[]};
const canSetup=()=>currentProfile&&['admin','supervisor'].includes(currentProfile.role);
const canQC=()=>currentProfile&&['admin','supervisor','qc'].includes(currentProfile.role);
const qEsc=v=>esc(v);
const uid=()=>currentProfile?.id;
const colorDefaults={pass:'#DCF2E6',fail:'#F9DFDF',pending:'#FFF0D2'};
function qcMsg(id,msg,type='ok'){const el=$(id);if(!el)return;el.innerHTML=msg?`<div class="notice ${type}">${qEsc(msg)}</div>`:'';if(msg)setTimeout(()=>{el.innerHTML=''},4000)}
async function qcWriteAudit(action,module,record_number,new_data=null,old_data=null){try{await cloud.from('audit_logs').insert({action,module,record_type:'qc',record_number,old_data,new_data})}catch(e){console.warn('QC audit',e)}}
async function loadQCProjects(){if(!canQC())return;const [p,c]=await Promise.all([cloud.from('qc_projects').select('*').is('deleted_at',null).eq('is_active',true).order('name'),cloud.from('qc_project_columns').select('*').is('deleted_at',null).order('display_order')]);if(p.error)throw p.error;if(c.error)throw c.error;qcState.projects=p.data||[];qcState.columns=c.data||[];refreshQCProjectSelects();renderProjectList()}
function refreshQCProjectSelects(){const opts='<option value="">Select project</option>'+qcState.projects.map(p=>`<option value="${p.id}">${qEsc(p.name)}</option>`).join('');if($('qcProjectSelect'))$('qcProjectSelect').innerHTML=opts;if($('qcFilterProject'))$('qcFilterProject').innerHTML='<option value="">All projects</option>'+qcState.projects.map(p=>`<option value="${p.id}">${qEsc(p.name)}</option>`).join('')}
function defaultCol(){return {id:crypto.randomUUID(),column_name:'',data_type:'decimal',unit:'',is_required:true,decimal_places:2,min_value:'',max_value:'',dropdown_options:'',pass_color:colorDefaults.pass,fail_color:colorDefaults.fail,pending_color:colorDefaults.pending}}
function renderBuilder(){const host=$('qcColumnBuilder');if(!host)return;if(!qcState.builderColumns.length)qcState.builderColumns=[defaultCol()];host.innerHTML=qcState.builderColumns.map((c,i)=>`<div class="qc-column-row" data-i="${i}">
<div><label>Column Name</label><input data-k="column_name" value="${qEsc(c.column_name||'')}" placeholder="PVC"></div>
<div><label>Type</label><select data-k="data_type"><option value="integer" ${c.data_type==='integer'?'selected':''}>Integer</option><option value="decimal" ${c.data_type==='decimal'?'selected':''}>Decimal</option><option value="text" ${c.data_type==='text'?'selected':''}>Text</option><option value="dropdown" ${c.data_type==='dropdown'?'selected':''}>Dropdown</option><option value="pass_fail" ${c.data_type==='pass_fail'?'selected':''}>Pass / Fail</option></select></div>
<div><label>Unit</label><input data-k="unit" value="${qEsc(c.unit||'')}" placeholder="DPPM / %"></div>
<div><label>Decimals</label><input data-k="decimal_places" type="number" min="0" max="6" value="${c.decimal_places??2}"></div>
<div><label>Min Pass</label><input data-k="min_value" type="number" step="any" value="${c.min_value??''}"></div>
<div><label>Max Pass</label><input data-k="max_value" type="number" step="any" value="${c.max_value??''}"></div>
<div><label>PASS</label><input class="color-input" data-k="pass_color" type="color" value="${c.pass_color||colorDefaults.pass}"></div>
<div><label>FAIL</label><input class="color-input" data-k="fail_color" type="color" value="${c.fail_color||colorDefaults.fail}"></div>
<div><label>PENDING</label><input class="color-input" data-k="pending_color" type="color" value="${c.pending_color||colorDefaults.pending}"></div>
<div><button class="icon-btn danger qc-remove-col" type="button" data-i="${i}">×</button></div>
<div style="grid-column:1/-1"><label>Dropdown Options (comma separated; only used for Dropdown)</label><input data-k="dropdown_options" value="${qEsc(Array.isArray(c.dropdown_options)?c.dropdown_options.join(', '):(c.dropdown_options||''))}" placeholder="PASS, FAIL, PENDING"></div>
</div>`).join('');host.querySelectorAll('[data-k]').forEach(el=>el.oninput=()=>{const i=Number(el.closest('.qc-column-row').dataset.i);qcState.builderColumns[i][el.dataset.k]=el.value});host.querySelectorAll('.qc-remove-col').forEach(b=>b.onclick=()=>{qcState.builderColumns.splice(Number(b.dataset.i),1);renderBuilder()})}
function resetBuilder(){qcState.builderColumns=[defaultCol()];$('qcProjectId').value='';$('qcProjectName').value='';$('qcProjectDescription').value='';$('qcCancelProjectEdit').hidden=true;renderBuilder()}
async function saveProject(){if(!canSetup())return;const name=$('qcProjectName').value.trim();if(!name)return qcMsg('qcProjectMessage','Project name is required.','bad');if(!qcState.builderColumns.length||qcState.builderColumns.some(c=>!String(c.column_name||'').trim()))return qcMsg('qcProjectMessage','Every column needs a name.','bad');const id=$('qcProjectId').value;const payload={name,description:$('qcProjectDescription').value.trim()||null,is_active:true,updated_by:uid(),updated_at:new Date().toISOString()};let projectId=id;if(id){const old=qcState.projects.find(x=>x.id===id);const {error}=await cloud.from('qc_projects').update(payload).eq('id',id);if(error)return qcMsg('qcProjectMessage',error.message,'bad');await cloud.from('qc_project_columns').update({deleted_at:new Date().toISOString()}).eq('project_id',id).is('deleted_at',null);await qcWriteAudit('UPDATE QC PROJECT','qc_project',name,payload,old)}else{payload.created_by=uid();const {data,error}=await cloud.from('qc_projects').insert(payload).select('id').single();if(error)return qcMsg('qcProjectMessage',error.message,'bad');projectId=data.id;await qcWriteAudit('CREATE QC PROJECT','qc_project',name,payload)}const rows=qcState.builderColumns.map((c,i)=>({project_id:projectId,column_name:String(c.column_name).trim(),data_type:c.data_type,unit:String(c.unit||'').trim()||null,is_required:true,decimal_places:Number(c.decimal_places)||0,min_value:c.min_value===''?null:Number(c.min_value),max_value:c.max_value===''?null:Number(c.max_value),dropdown_options:c.data_type==='dropdown'?String(c.dropdown_options||'').split(',').map(x=>x.trim()).filter(Boolean):[],pass_color:c.pass_color||colorDefaults.pass,fail_color:c.fail_color||colorDefaults.fail,pending_color:c.pending_color||colorDefaults.pending,display_order:i+1,created_by:uid()}));const {error:ce}=await cloud.from('qc_project_columns').insert(rows);if(ce)return qcMsg('qcProjectMessage',ce.message,'bad');qcMsg('qcProjectMessage','QC Project saved.');resetBuilder();await loadQCProjects()}
function renderProjectList(){const host=$('qcProjectList');if(!host)return;if(!canSetup()){host.innerHTML='<div class="empty">Supervisor or Admin permission required.</div>';return}host.innerHTML=qcState.projects.length?qcState.projects.map(p=>{const count=qcState.columns.filter(c=>c.project_id===p.id&&!c.deleted_at).length;return `<div class="list-row"><div><strong>${qEsc(p.name)}</strong><div class="muted">${count} columns${p.description?' · '+qEsc(p.description):''}</div></div><div class="row-actions"><button class="icon-btn" onclick="window.editQCProject('${p.id}')">Edit</button><button class="icon-btn" onclick="window.deleteQCProject('${p.id}')">Delete</button></div></div>`}).join(''):'<div class="empty">No QC projects yet.</div>'}
window.editQCProject=id=>{const p=qcState.projects.find(x=>x.id===id);if(!p)return;$('qcProjectId').value=id;$('qcProjectName').value=p.name;$('qcProjectDescription').value=p.description||'';qcState.builderColumns=qcState.columns.filter(c=>c.project_id===id&&!c.deleted_at).sort((a,b)=>a.display_order-b.display_order).map(c=>({...c,dropdown_options:Array.isArray(c.dropdown_options)?c.dropdown_options.join(', '):''}));$('qcCancelProjectEdit').hidden=false;renderBuilder();document.querySelector('[data-tab="qc-projects"]').click()};
window.deleteQCProject=async id=>{if(!canSetup()||!confirm('Delete this QC project? Existing QC files will remain in the system.'))return;const p=qcState.projects.find(x=>x.id===id);const {error}=await cloud.from('qc_projects').update({deleted_at:new Date().toISOString(),is_active:false,updated_by:uid(),updated_at:new Date().toISOString()}).eq('id',id);if(error)return alert(error.message);await qcWriteAudit('DELETE QC PROJECT','qc_project',p?.name||id,{deleted:true});await loadQCProjects()};
async function createQCFile(){if(!canQC())return;const projectId=$('qcProjectSelect').value;if(!projectId)return qcMsg('qcEntryMessage','Please select a QC project.','bad');const project=qcState.projects.find(p=>p.id===projectId),cols=qcState.columns.filter(c=>c.project_id===projectId&&!c.deleted_at).sort((a,b)=>a.display_order-b.display_order);if(!project||!cols.length)return qcMsg('qcEntryMessage','This project has no columns.','bad');const snapshot=cols.map(c=>({column_name:c.column_name,data_type:c.data_type,unit:c.unit,is_required:c.is_required,decimal_places:c.decimal_places,min_value:c.min_value,max_value:c.max_value,dropdown_options:c.dropdown_options||[],pass_color:c.pass_color,fail_color:c.fail_color,pending_color:c.pending_color,display_order:c.display_order}));const {data,error}=await cloud.rpc('create_qc_file',{p_project_id:projectId,p_project_name:project.name,p_schema:snapshot});if(error)return qcMsg('qcEntryMessage',error.message,'bad');qcState.currentFile=data;qcState.currentRows=Array.from({length:5},(_,i)=>({id:null,row_no:i+1,values:{}}));renderQCEditor();await loadQCFiles();await qcWriteAudit('CREATE QC FILE','qc_file',data.file_number,{project:project.name})}
function evaluate(col,val){if(val===null||val===undefined||String(val).trim()==='')return 'pending';if(col.data_type==='pass_fail'){const s=String(val).toUpperCase();return s==='PASS'?'pass':s==='FAIL'?'fail':'pending'}if(['integer','decimal'].includes(col.data_type)){const x=Number(val);if(!Number.isFinite(x))return 'fail';if(col.min_value!==null&&col.min_value!==''&&x<Number(col.min_value))return 'fail';if(col.max_value!==null&&col.max_value!==''&&x>Number(col.max_value))return 'fail';return 'pass'}return 'pending'}
function inputFor(col,rowIndex,value){const key=qEsc(col.column_name),v=value??'';let input;if(col.data_type==='dropdown'){const opts=Array.isArray(col.dropdown_options)?col.dropdown_options:[];input=`<select class="qc-cell" data-row="${rowIndex}" data-col="${key}"><option value=""></option>${opts.map(o=>`<option ${String(v)===String(o)?'selected':''}>${qEsc(o)}</option>`).join('')}</select>`}else if(col.data_type==='pass_fail'){input=`<select class="qc-cell" data-row="${rowIndex}" data-col="${key}"><option value=""></option><option ${v==='PASS'?'selected':''}>PASS</option><option ${v==='FAIL'?'selected':''}>FAIL</option><option ${v==='PENDING'?'selected':''}>PENDING</option></select>`}else{const type=['integer','decimal'].includes(col.data_type)?'number':'text',step=col.data_type==='decimal'?'any':'1';input=`<input class="qc-cell" data-row="${rowIndex}" data-col="${key}" type="${type}" ${type==='number'?`step="${step}"`:''} value="${qEsc(v)}">`}return input}
function renderQCEditor(){const f=qcState.currentFile;if(!f){$('qcEditorCard').style.display='none';return}$('qcEditorCard').style.display='block';$('qcEditorTitle').textContent=f.project_name_snapshot||'QC File';$('qcEditorSubtitle').textContent='Enter QC results. Cell colors are determined by the project rules.';$('qcFileNumber').textContent=f.file_number;$('qcFileStatus').textContent=f.status||'draft';const cols=f.project_schema||[];$('qcGridHost').innerHTML=`<div class="qc-grid-wrap"><table class="qc-grid"><thead><tr><th>#</th>${cols.map(c=>`<th>${qEsc(c.column_name)}${c.unit?`<div class="muted">${qEsc(c.unit)}</div>`:''}</th>`).join('')}<th>Result</th></tr></thead><tbody>${qcState.currentRows.map((r,ri)=>`<tr><td>${ri+1}</td>${cols.map(c=>`<td>${inputFor(c,ri,r.values?.[c.column_name])}</td>`).join('')}<td class="qc-result" data-result="${ri}">Pending</td></tr>`).join('')}</tbody></table></div>`;bindGrid();refreshRowResults()}
function bindGrid(){document.querySelectorAll('.qc-cell').forEach(el=>{const handler=()=>{const r=Number(el.dataset.row),c=el.dataset.col;qcState.currentRows[r].values[c]=el.value;refreshRowResults()};el.addEventListener('input',handler);el.addEventListener('change',handler)})}
function refreshRowResults(){const f=qcState.currentFile;if(!f)return;const cols=f.project_schema||[];qcState.currentRows.forEach((r,ri)=>{let hasFail=false,hasPending=false;cols.forEach(c=>{const el=document.querySelector(`.qc-cell[data-row="${ri}"][data-col="${CSS.escape(c.column_name)}"]`);if(!el)return;const status=evaluate(c,r.values?.[c.column_name]);el.style.backgroundColor=status==='pass'?c.pass_color||colorDefaults.pass:status==='fail'?c.fail_color||colorDefaults.fail:c.pending_color||colorDefaults.pending;hasFail ||= status==='fail';hasPending ||= status==='pending'});const result=hasFail?'FAIL':hasPending?'PENDING':'PASS',cell=document.querySelector(`[data-result="${ri}"]`);if(cell){cell.textContent=result;cell.className='qc-result '+(result==='PASS'?'qc-status-pass':result==='FAIL'?'qc-status-fail':'qc-status-pending')}})}
async function saveQCFile(){const f=qcState.currentFile;if(!f)return;const rows=qcState.currentRows.map((r,i)=>({file_id:f.id,row_no:i+1,values:r.values||{},created_by:uid(),updated_by:uid(),updated_at:new Date().toISOString()}));const {error:delErr}=await cloud.from('qc_file_rows').update({deleted_at:new Date().toISOString()}).eq('file_id',f.id).is('deleted_at',null);if(delErr)return qcMsg('qcSaveMessage',delErr.message,'bad');const {error}=await cloud.from('qc_file_rows').insert(rows);if(error)return qcMsg('qcSaveMessage',error.message,'bad');await cloud.from('qc_files').update({updated_by:uid(),updated_at:new Date().toISOString()}).eq('id',f.id);await qcWriteAudit('EDIT QC DATA','qc_file',f.file_number,{rows:rows.length});qcMsg('qcSaveMessage','QC data saved.');await loadQCFiles()}
async function loadQCFiles(){if(!canQC())return;const {data,error}=await cloud.from('qc_files').select('id,file_number,project_id,project_name_snapshot,project_schema,status,created_at,updated_at,created_by,profiles:created_by(full_name,email)').is('deleted_at',null).order('created_at',{ascending:false}).limit(500);if(error){if($('qcFilesTable'))$('qcFilesTable').innerHTML=`<div class="notice bad">${qEsc(error.message)}</div>`;return}qcState.files=data||[];renderQCFiles()}
function renderQCFiles(){const host=$('qcFilesTable');if(!host)return;let rows=[...qcState.files],date=$('qcFilterDate')?.value,project=$('qcFilterProject')?.value,user=($('qcFilterUser')?.value||'').toLowerCase(),search=($('qcFilterSearch')?.value||'').toLowerCase();if(date)rows=rows.filter(r=>r.created_at?.slice(0,10)===date);if(project)rows=rows.filter(r=>r.project_id===project);if(user)rows=rows.filter(r=>((r.profiles?.full_name||'')+' '+(r.profiles?.email||'')).toLowerCase().includes(user));if(search)rows=rows.filter(r=>(r.file_number||'').toLowerCase().includes(search));host.innerHTML=rows.length?`<div class="table-wrap"><table><thead><tr><th>File</th><th>Project</th><th>Created</th><th>Created By</th><th>Status</th><th>Action</th></tr></thead><tbody>${rows.map(r=>`<tr><td><strong>${qEsc(r.file_number)}</strong></td><td>${qEsc(r.project_name_snapshot||'-')}</td><td>${new Date(r.created_at).toLocaleString('en-MY')}</td><td>${qEsc(r.profiles?.full_name||r.profiles?.email||'-')}</td><td>${qEsc(r.status||'draft')}</td><td><button class="icon-btn" onclick="window.openQCFile('${r.id}')">Open / Edit</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No QC files found.</div>'}
window.openQCFile=async id=>{const f=qcState.files.find(x=>x.id===id);if(!f)return;const {data,error}=await cloud.from('qc_file_rows').select('id,row_no,values').eq('file_id',id).is('deleted_at',null).order('row_no');if(error)return alert(error.message);qcState.currentFile=f;qcState.currentRows=(data&&data.length)?data:Array.from({length:5},(_,i)=>({id:null,row_no:i+1,values:{}}));document.querySelector('[data-tab="qc-entry"]').click();renderQCEditor()};
function exportQCExcel(){const f=qcState.currentFile;if(!f||!window.XLSX)return alert('Excel export library is not available.');const cols=f.project_schema||[],aoa=[[f.project_name_snapshot],[`File: ${f.file_number}`],[],['#',...cols.map(c=>c.column_name+(c.unit?` (${c.unit})`:''))],...qcState.currentRows.map((r,i)=>[i+1,...cols.map(c=>r.values?.[c.column_name]??'')])];const ws=XLSX.utils.aoa_to_sheet(aoa),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'QC');XLSX.writeFile(wb,`${f.file_number}.xlsx`);qcWriteAudit('EXPORT EXCEL','qc_file',f.file_number)}
function exportQCPdf(){const f=qcState.currentFile;if(!f||!window.jspdf)return alert('PDF export library is not available.');const {jsPDF}=window.jspdf,doc=new jsPDF({orientation:'landscape'}),cols=f.project_schema||[];doc.setFontSize(15);doc.text(f.project_name_snapshot||'QC File',14,14);doc.setFontSize(10);doc.text(`File: ${f.file_number}`,14,20);doc.autoTable({startY:25,head:[['#',...cols.map(c=>c.column_name+(c.unit?` (${c.unit})`:''))]],body:qcState.currentRows.map((r,i)=>[i+1,...cols.map(c=>String(r.values?.[c.column_name]??''))]),styles:{fontSize:8}});doc.save(`${f.file_number}.pdf`);qcWriteAudit('EXPORT PDF','qc_file',f.file_number)}
function hook(){if($('qcAddColumn'))$('qcAddColumn').onclick=()=>{qcState.builderColumns.push(defaultCol());renderBuilder()};if($('qcSaveProject'))$('qcSaveProject').onclick=saveProject;if($('qcCancelProjectEdit'))$('qcCancelProjectEdit').onclick=resetBuilder;if($('qcRefreshProjects'))$('qcRefreshProjects').onclick=loadQCProjects;if($('qcCreateFile'))$('qcCreateFile').onclick=createQCFile;if($('qcAddRow'))$('qcAddRow').onclick=()=>{qcState.currentRows.push({id:null,row_no:qcState.currentRows.length+1,values:{}});renderQCEditor()};if($('qcSaveFile'))$('qcSaveFile').onclick=saveQCFile;if($('qcExportXlsx'))$('qcExportXlsx').onclick=exportQCExcel;if($('qcExportPdf'))$('qcExportPdf').onclick=exportQCPdf;if($('qcRefreshFiles'))$('qcRefreshFiles').onclick=loadQCFiles;['qcFilterDate','qcFilterProject','qcFilterUser','qcFilterSearch'].forEach(id=>{if($(id))$(id).addEventListener('input',renderQCFiles)});document.querySelectorAll('[data-tab="qc-entry"],[data-tab="qc-files"],[data-tab="qc-projects"]').forEach(btn=>btn.addEventListener('click',()=>{if(btn.dataset.tab==='qc-files')loadQCFiles();if(btn.dataset.tab==='qc-projects')loadQCProjects()}));resetBuilder()}
window.addEventListener('fgms:profile',async e=>{if(canQC()){await loadQCProjects();await loadQCFiles()}});
document.addEventListener('DOMContentLoaded',hook);
})();
